### ISSUE TITLE
Parse eror

### ISSUE THREAD

**Issue by c0b41** [matthewmueller/mini-html-parser#1]
Why did I get this error

![adsz](https://f.cloud.github.com/assets/2834954/2036739/c87ffb36-8953-11e3-83f1-a466518664f6.png)

**Comment by matthewmueller** [comment]
Can you send me the HTML around that area?

**Comment by c0b41** [comment]
[checkout](http://requirebin.com/?gist=8750905)

**Comment by matthewmueller** [comment]
probably not valid html, getting a bunch of errors trying to validate it at http://validator.w3.org/. you're probably missing a closing tag.

**Comment by c0b41** [comment]
yes i have problems because of it thanks :+1:
